backup:
  downgrade: false
  enabled: true
  install: false
  mode: incremental
  type: rsync
  uninstall: false
  upgrade: false
boot:
  load_apps: true
disk:
  trim:
    after_upgrade: false
download:
  icons: true
  multithreaded: true
  multithreaded_client: null
gems: null
locale: null
memory_cache:
  data_expiration: 3600
  icon_expiration: 300
store_root_password: true
suggestions:
  by_type: 10
  enabled: true
system:
  notifications: true
  single_dependency_checking: false
ui:
  auto_scale: false
  hdpi: true
  qt_style: fusion
  scale_factor: 1.0
  style: null
  system_theme: false
  table:
    max_displayed: 50
  theme: light
  tray:
    default_icon: null
    updates_icon: null
updates:
  ask_for_reboot: false
  check_interval: 30
